import {useEffect,useState} from 'react';
type MetricRow={user_id:string;signup_date:string;last_active:string|null;questions:number;successful_answers:number;is_returning:boolean};
type Series={period:string;users:number}[];
type AccountRow={email:string;created_at:string;last_login_at:string|null;login_count:number;questions:number;uploads?:number};
type UploadRow={created_at:string;outcome:string;files:number;figures:number;reason:string|null;email:string|null};
type UploadMetrics={total_uploads:number;read_ok:number;not_read:number;uploads_today:number;uploads_7_days:number;people_uploading:number;by_outcome:Record<string,number>;by_day:{period:string;uploads:number;read_ok:number}[];recent:UploadRow[]};
const OUTCOME:Record<string,string>={read:'Read successfully',no_aid_lines:'No aid figures found',unreadable:'Could not match figures',privacy_blocked:'Blocked for privacy',reader_error:'Reader error'};
type AccountMetrics={total_accounts:number;accounts_today:number;accounts_7_days:number;accounts_30_days:number;logins_today:number;active_accounts_7_days:number;accounts_by_day:{period:string;accounts:number}[];accounts:AccountRow[]};
type Metrics=Record<string,unknown>&{users:MetricRow[];signups_by_day:Series;signups_by_week:Series;signups_by_month:Series;accounts?:AccountMetrics|null;uploads?:UploadMetrics|null};
export function BetaAdmin(){
 const [email,setEmail]=useState(''),[code,setCode]=useState(''),[sent,setSent]=useState(false);
 const [data,setData]=useState<Metrics|null>(null),[error,setError]=useState('');
 useEffect(()=>{void fetch('/api/beta-admin',{cache:'no-store',credentials:'same-origin'}).then(async r=>{if(!r.ok)throw Error(r.status===401?'Sign in with your invited administrator account, then reload.':r.status===403?'Administrator access is required.':'Beta metrics are not available yet.');return r.json();}).then(setData).catch(e=>setError(e.message));},[]);
 async function signIn(){try{const r=await fetch('/api/beta-auth',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:sent?'verify':'send',email,code})});if(!r.ok)throw Error('Administrator sign-in failed.');if(sent)window.location.reload();else setSent(true);}catch{setError('Administrator sign-in failed. Check your invitation and code.');}}
 return <main style={{padding:'40px',maxWidth:1200,margin:'auto'}}><h1>Fynliq beta usage</h1>{!data&&<form onSubmit={e=>{e.preventDefault();void signIn();}}><label>Administrator email<input type="email" required value={email} onChange={e=>setEmail(e.target.value)}/></label>{sent&&<label>Email code<input required autoComplete="one-time-code" value={code} onChange={e=>setCode(e.target.value)}/></label>}<button>{sent?'Verify code':'Send sign-in code'}</button></form>}
 {error&&<p role="alert">{error}</p>}
 {data&&<>
 <section><h2>Document uploads</h2>{data.uploads?<><dl>{([['total_uploads','Total uploads'],['read_ok','Read successfully'],['not_read','Not read'],['uploads_today','Uploads today'],['uploads_7_days','Uploads, last 7 days'],['people_uploading','People who uploaded']] as const).map(([key,label])=><div key={key}><dt>{label}</dt><dd>{data.uploads?.[key]}</dd></div>)}</dl>
 <table><thead><tr><th>Day (UTC)</th><th>Uploads</th><th>Read successfully</th></tr></thead><tbody>{data.uploads.by_day.map(d=><tr key={d.period}><td>{d.period}</td><td>{d.uploads}</td><td>{d.read_ok}</td></tr>)}</tbody></table>
 <h3>Latest uploads</h3><table><thead><tr><th>When</th><th>Account</th><th>Result</th><th>Files</th><th>Figures read</th><th>Reason code</th></tr></thead><tbody>{data.uploads.recent.map((u,i)=><tr key={i}><td>{u.created_at}</td><td>{u.email||'Guest'}</td><td>{OUTCOME[u.outcome]||u.outcome}</td><td>{u.files}</td><td>{u.figures}</td><td>{u.reason||''}</td></tr>)}</tbody></table>
 <p>Only the outcome and counts are stored. File names, document text, figures and images are never saved.</p></>:<p>Upload tracking is not set up yet.</p>}</section>
 <section><h2>Accounts (log-in page)</h2>{data.accounts?<><dl>{([['total_accounts','Total accounts'],['accounts_today','New accounts today'],['accounts_7_days','New accounts, last 7 days'],['accounts_30_days','New accounts, last 30 days'],['logins_today','Log-ins today'],['active_accounts_7_days','Accounts that logged in, last 7 days']] as const).map(([key,label])=><div key={key}><dt>{label}</dt><dd>{data.accounts?.[key]}</dd></div>)}</dl>
 <table><thead><tr><th>Email</th><th>Signed up</th><th>Last log-in</th><th>Log-ins</th><th>Questions asked</th><th>Uploads</th></tr></thead><tbody>{data.accounts.accounts.map(a=><tr key={a.email}><td>{a.email}</td><td>{a.created_at}</td><td>{a.last_login_at||'Never'}</td><td>{a.login_count}</td><td>{a.questions}</td><td>{a.uploads??0}</td></tr>)}</tbody></table></>:<p>Account tracking is not set up yet: run supabase/migrations/202609210001_accounts_tracking.sql in the Supabase SQL editor.</p>}</section>
 <p>DAU counts question submissions today (UTC). WAU and MAU count distinct users submitting questions in the last 7 and 30 days. Returning means questions on at least two distinct UTC days. IDs represent guest browsers, not verified people. Page views and login alone do not count.</p>
 <dl>{[['total_signups','Total guest signups'],['activated_users','Activated users'],['returning_users','Returning users'],['dau','DAU'],['wau','WAU'],['mau','MAU'],['total_questions','Total questions'],['successful_answers','Successful answers'],['failed_answers','Failed answers'],['pending_answers','Pending answers'],['questions_per_user','Questions per user'],['new_today','New users today'],['new_7_days','New users: 7 days'],['new_30_days','New users: 30 days']].map(([key,label])=><div key={key}><dt>{label}</dt><dd>{String(data[key]??0)}</dd></div>)}</dl>
 {(['day','week','month'] as const).map(period=><section key={period}><h2>Signups by {period} (UTC)</h2><table><thead><tr><th>Period</th><th>New users</th></tr></thead><tbody>{data[`signups_by_${period}`].map(row=><tr key={row.period}><td>{row.period}</td><td>{row.users}</td></tr>)}</tbody></table></section>)}
 <h2>Participants</h2><table><thead><tr><th>Internal ID</th><th>First joined</th><th>Last meaningful activity</th><th>Questions</th><th>Successful answers</th></tr></thead><tbody>{data.users.map(u=><tr key={u.user_id}><td>{u.user_id}</td><td>{u.signup_date}</td><td>{u.last_active||'No questions yet'}</td><td>{u.questions}</td><td>{u.successful_answers}</td></tr>)}</tbody></table>
 <button onClick={()=>void fetch('/api/beta-auth',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'admin-logout'})}).then(r=>{if(r.ok)window.location.reload();else setError('Could not sign out. Try again.');})}>Sign out of admin</button><p>No question text, answer text, filenames or financial details are collected in these metrics. Unfinished requests older than two minutes count as failed until a final outcome is recorded.</p>
 </>}
 </main>;
}
